* MOSCOW Analysis
** MUST
*** M1: TheTideTorrent MUST parse metainfo file (*.torrent).
**** Decoding
Retrieve information from torrent file.
**** Bencoding
It is encoding data.
*** M2: TheTideTorrent MUST retreive other peers which will/may communicate with. 
**** Tracker HTTP/HTTPS Protocol  
Client --request--> Tracker
Tracker --response--> Client
*** M3: TheTideTorrent MUST connect to peers 
**** Peer Wire Protocol  
***** Handshake
BTC opens a port for local peer and listens on this port for incoming connections.
BTC must inform Tracker about this port. 
Remote peer must connects over a TCP channel 
Remote peer then transmits a first required message to complete handshake.
The structure of a handshake message is string of bytes as follows;
 _____________ ________________________________________________
| Name Length | Protocol Name | Reserved | Info Hash | Peer ID |
|_____________|_______________|__________|___________|_________|

*** M4: User MUST be able to download from connected peers
**** Peer Wire Protocol 
Once handshake has been completed, both remote and local peer can send asynchronous message to each other.
The message contains state of local peer and transferring data.

*** M5: User MUST be able to share complete pieces with others.
**** Peer Wire Protocol 
Once handsake is completed and a piece of data is downloaded, remote peer uploads while local peer downloads. 

** SHOULD
*** S1: User SHOULD select where to save the file locally.
